# Generated by Django 2.1.5 on 2019-05-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunflower', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dish_weight',
        ),
        migrations.AddField(
            model_name='recipe',
            name='person_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.URLField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='photo',
            field=models.ImageField(blank=True, upload_to='files/media/'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='photo',
            field=models.ImageField(blank=True, upload_to='files/media/'),
        ),
    ]
