# Generated by Django 2.1.5 on 2019-05-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunflower', '0002_auto_20190506_0146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-rating__rating', '-publish_date')},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='files/media/'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='files/media/'),
        ),
    ]
