version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
    env_file:
      - .env
  web:
    build: .
    command:
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
